name: "Test"
on:
  push:
  pull_request:

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2
      - name: Install Prerequisites
        run: bin/install_prerequisites_ubuntu.sh
      - name: Install Rust
        run: bin/install_rust.sh
      - name: Build
        run: bin/build.sh
      - name: Unit tests
        run: bin/test.sh
